version: "3.8"
services:
  data:
    build:
      dockerfile: Dockerfile
      context: ./data
    volumes:
      - ./data:/app
    ports:
      - 3080:3080
  client:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    depends_on:
      - data
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
  server:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - 8080:8080
